//! Conflict Analysis

#[cfg(feature = "boundary_check")]
use crate::assign::DebugReportIF;
#[cfg(feature = "trail_saving")]
use crate::assign::TrailSavingIF;

use {
    super::State,
    crate::{
        assign::{AssignIF, AssignStack, PropagateIF, VarManipulateIF},
        cdb::{ClauseDB, ClauseDBIF},
        types::*,
    },
    std::collections::HashSet,
};

/// returns:
/// - 0: if a new assignment is generated by conflict analysis.
/// - 1: if a binary link is generated
/// - otherwise: it's the LBD of the learnt clause.
#[allow(clippy::cognitive_complexity)]
pub fn handle_conflict(
    asg: &mut AssignStack,
    cdb: &mut ClauseDB,
    state: &mut State,
    cc: &ConflictContext,
) -> Result<u16, SolverError> {
    // `conflicting_level` should be calculated from cc.1 instead of cc.0.
    // Because the conflicting_literal has two values assigned at different levels.
    // We need larger one.
    #[cfg(feature = "chrono_BT")]
    let conflicting_level; // for now
    #[cfg(not(feature = "chrono_BT"))]
    let conflicting_level = asg.decision_level();

    // we need a catch here for handling the possibility of level zero conflict
    // at higher level due to the incoherence between the current level and conflicting
    // level in chronoBT. This leads to UNSAT solution. No need to update misc stats.
    {
        if let AssignReason::Implication(cid) = cc.1
            && cdb[cid].iter().all(|l| asg.level(l.vi()) == 0)
        {
            return Err(SolverError::RootLevelConflict(*cc));
        }
    }

    #[cfg(feature = "chrono_BT")]
    match cc.1 {
        AssignReason::BinaryLink(l) => {
            conflicting_level = asg.var(l.vi()).level.max(asg.var(cc.0.vi()).level);
        }
        AssignReason::Implication(cid) => {
            let c = &cdb[cid];
            conflicting_level = c.iter().map(|l| asg.level(l.vi())).max().unwrap();
            if 1 == c
                .iter()
                .filter(|l| asg.level(l.vi()) == conflicting_level)
                .count()
            {
                if let Some(second_level) = c
                    .iter()
                    .map(|l| asg.level(l.vi()))
                    .filter(|l| *l < conflicting_level)
                    .max()
                {
                    debug_assert!(0 < second_level);
                    asg.cancel_until(second_level);
                    return Ok(c.rank);
                }
            }
        }
        _ => {
            panic!();
        }
    }
    asg.cancel_until(conflicting_level);
    asg.handle(SolverEvent::Conflict);

    let assign_level = conflict_analyze(asg, cdb, state, cc).max(asg.root_level());
    // Reorder LRAT hints for the checker.
    //
    // Conflict analysis collects hints in trail-backward order (last propagated
    // first).  LRAT checkers process hints sequentially and each hint clause
    // must be unit (or empty) under the current partial assignment at the time
    // it is reached.
    //
    // Root-level unit clauses (input or previously learned) justify literals
    // that are unconditionally true; they must appear *before* any clause that
    // relies on those literals.  Non-root hints are collected backwards along
    // the trail and need to be reversed to restore forward-propagation order.
    //
    // Strategy: partition into root-level hints and non-root hints, deduplicate
    // each group, then concatenate root-first followed by reversed non-root.
    #[cfg(not(feature = "no_IO"))]
    {
        // Build a set of LRAT IDs that correspond to root-level assignments.
        let root_id_set: std::collections::HashSet<u64> = state
            .lrat_root_ids
            .iter()
            .copied()
            .filter(|&id| id != 0)
            .collect();
        let mut root_hints: Vec<u64> = Vec::new();
        let mut nonroot_hints: Vec<u64> = Vec::new();
        let mut seen = std::collections::HashSet::new();
        for &id in state.lrat_hints.iter() {
            if id == 0 || !seen.insert(id) {
                continue;
            }
            if root_id_set.contains(&id) {
                root_hints.push(id);
            } else {
                nonroot_hints.push(id);
            }
        }
        nonroot_hints.reverse();
        state.lrat_hints.clear();
        state.lrat_hints.extend_from_slice(&root_hints);
        state.lrat_hints.append(&mut nonroot_hints);
    }
    let new_learnt = &mut state.new_learnt;
    let learnt_len = new_learnt.len();
    if learnt_len == 0 {
        #[cfg(feature = "boundary_check")]
        {
            println!(
                "empty learnt at {}({}) by {:?}",
                cl,
                asg.reason(asg.decision_vi(cl)).is_none(),
                asg.dump(asg, &cdb[ci]),
            );
        }
        return Err(SolverError::EmptyClause);
    }
    let l0 = new_learnt[0];
    if learnt_len == 1 {
        //
        //## A NEW ASSERTION by UNIT LEARNT CLAUSE GENERATION
        //
        match asg.assigned(l0) {
            Some(true) if asg.root_level() < asg.level(l0.vi()) => {
                panic!("double assignment occurred");
                // asg.lift_to_asserted(l0.vi());
            }
            Some(false) if asg.level(l0.vi()) == asg.root_level() => {
                return Err(SolverError::RootLevelConflict((l0, asg.reason(l0.vi()))));
            }
            _ => {
                // dump to certified even if it's a literal.
                #[cfg(not(feature = "no_IO"))]
                {
                    let lrat_id = cdb.certificate_add_assertion_lrat(l0, &state.lrat_hints);
                    state.lrat_root_ids[l0.vi()] = lrat_id;
                }
                #[cfg(feature = "no_IO")]
                cdb.certificate_add_assertion(l0);
                if asg.assign_at_root_level(l0).is_err() {
                    unreachable!("handle_conflict::root_level_conflict_by_assertion");
                }
                let vi = l0.vi();
                state.restart.handle(SolverEvent::Assert(vi));
                cdb.handle(SolverEvent::Assert(vi));
                return Ok(0);
            }
        }
    }
    let l1 = new_learnt[1];
    // assert: root_level < cl, which was checked already by new_learnt.is_empty().

    // NCB places firstUIP on level bl, while CB does it on level cl.
    // ?? || Therefore the condition to use CB is: activity(firstUIP) < activity(v(bl)).
    // PREMISE: root_level < bl, because asg.decision_vi accepts only non-zero values.

    // At the present time, some reason clauses can contain first UIP or its negation.
    // So we have to filter vars instead of literals to avoid double counting.
    #[cfg(feature = "reason_side_rewarding")]
    let mut bumped = new_learnt.iter().map(|l| l.vi()).collect::<Vec<VarId>>();
    for lit in new_learnt.iter() {
        //
        //## Learnt Literal Rewarding
        //
        asg.reward_at_analysis(lit.vi());

        //
        //## Reason-Side Rewarding
        //
        #[cfg(feature = "reason_side_rewarding")]
        match asg.reason(lit.vi()) {
            AssignReason::BinaryLink(from) => {
                let vi = from.vi();
                if !bumped.contains(&vi) {
                    asg.reward_at_analysis(vi);
                    bumped.push(vi);
                }
            }
            AssignReason::Implication(r) => {
                for l in cdb[r].iter() {
                    let vi = l.vi();
                    if !bumped.contains(&vi) {
                        asg.reward_at_analysis(vi);
                        bumped.push(vi);
                    }
                }
            }
            AssignReason::Decision(_) => (),
            AssignReason::None => unreachable!("handle_conflict"),
        }
    }

    // learnt clause quality based backtrack strategy switching
    // Idea: If the learned clause is low quality, don’t trust it to justify a large backjump; use CBT/limited-backjump instead.
    let bt_drift: Option<bool> = if cfg!(feature = "chrono_BT")
        && assign_level > 0
        && asg
            .len_upto(conflicting_level)
            .saturating_sub(asg.len_upto(assign_level))
            >= 40
    {
        Some(true)
    } else if cfg!(feature = "BT_drift")
        && assign_level > 0
        && new_learnt
            .iter()
            .map(|l| asg.level(l.vi()))
            .collect::<HashSet<_>>()
            .len() as f64
            >= 2.5 * cdb.lbd.get().max(3.0)
    {
        Some(false)
    } else {
        None
    };
    asg.cancel_until(match bt_drift {
        None => assign_level,
        Some(false) => assign_level - 1,
        Some(true) => conflicting_level - 1,
    });
    if bt_drift.is_some() {
        #[cfg(feature = "trail_saving")]
        {
            asg.clear_saved_trail();
        }
        #[cfg(feature = "chrono_BT")]
        {
            state.num_chrono_bt += 1;
        }
    }
    // debug_assert_eq!(asg.assigned(l0), None);
    // debug_assert_eq!(
    //     new_learnt.iter().skip(1).map(|l| asg.level(l.vi())).max(),
    //     Some(assign_level)
    // );
    let rank: u16;
    match {
        #[cfg(not(feature = "no_IO"))]
        {
            cdb.new_clause_lrat(asg, new_learnt, &state.lrat_hints)
        }
        #[cfg(feature = "no_IO")]
        {
            cdb.new_clause(asg, new_learnt, true)
        }
    } {
        RefClause::Clause(cid) if learnt_len == 2 => {
            #[cfg(feature = "boundary_check")]
            cdb[cid].set_birth(asg.num_conflict);

            debug_assert_eq!(l0, cdb[cid].lit0());
            debug_assert_eq!(l1, cdb[cid].lit1());
            debug_assert_eq!(asg.assigned(l0), None);
            debug_assert!(bt_drift.is_some() || asg.assigned(l1) == Some(false));

            if bt_drift.is_none() {
                asg.assign_by_implication(l0, AssignReason::BinaryLink(!l1), assign_level);
                cdb[cid].used = cdb[cid].used.saturating_add(1);
            }
            rank = 1;
            #[cfg(feature = "bi_clause_completion")]
            cdb.complete_bi_clauses(asg);
        }
        RefClause::Clause(cid) => {
            #[cfg(feature = "boundary_check")]
            cdb[cid].set_birth(asg.num_conflict);

            debug_assert_eq!(cdb[cid].lit0(), l0);
            if bt_drift.is_none_or(|up1| up1 && cdb[cid].is_unit_under(&*asg)) {
                asg.assign_by_implication(l0, AssignReason::Implication(cid), assign_level);
                cdb[cid].used = cdb[cid].used.saturating_add(1);
            }
            rank = cdb[cid].rank;
        }
        RefClause::RegisteredClause(cid) => {
            debug_assert_eq!(learnt_len, 2);
            debug_assert!(
                (l0 == cdb[cid].lit0() && l1 == cdb[cid].lit1())
                    || (l0 == cdb[cid].lit1() && l1 == cdb[cid].lit0())
            );
            debug_assert_eq!(asg.assigned(l0), None);
            debug_assert!(bt_drift.is_some() || asg.assigned(l1) == Some(false));
            // if bt_drift.is_none() && asg.assigned(l1) != Some(false) {
            //     dbg!(cc);
            //     dbg!(asg.decision_level());
            //     dbg!(cid);
            //     for l in cdb[cid].iter() {
            //         println!("{:?} @ {} => {:?}", l, asg.level(l.vi()), asg.assigned(*l));
            //     }
            //     panic!("here we are!");
            // }
            rank = 1;
            if bt_drift.is_none_or(|up1| up1 && cdb[cid].is_unit_under(&*asg)) {
                asg.assign_by_implication(l0, AssignReason::BinaryLink(!l1), assign_level);
                cdb[cid].used = cdb[cid].used.saturating_add(1);
            }
        }
        RefClause::Dead => unreachable!("handle_conflict::RefClause::Dead"),
        RefClause::EmptyClause => unreachable!("handle_conflict::RefClause::EmptyClause"),
        RefClause::UnitClause(_) => unreachable!("handle_conflict::RefClause::UnitClause"),
    }
    state.c_lvl.update(conflicting_level as f64);
    state.b_lvl.update(assign_level as f64);
    state
        .e_mode
        .update(conflicting_level as f64 - assign_level as f64);
    Ok(rank)
}

///
/// ## Conflict Analysis
///
fn conflict_analyze(
    asg: &mut AssignStack,
    cdb: &mut ClauseDB,
    state: &mut State,
    cc: &ConflictContext,
) -> DecisionLevel {
    let learnt = &mut state.new_learnt;
    learnt.clear();
    learnt.push(Lit::from(u32::MAX));
    #[cfg(not(feature = "no_IO"))]
    state.lrat_hints.clear();
    let root_level = asg.root_level();
    // assert_eq!(asg.decision_level(), asg.var(cc.0.vi()).level);
    let dl = asg.decision_level();
    let mut path_cnt = 0;
    let &(mut p, mut reason) = cc;
    // assert_eq!(
    //     dl,
    //     asg.var(p.vi()).level,
    //     "conflict: {:?} occurred at a lower level than current dl",
    //     cc
    // );
    /// trace and reward the var
    macro_rules! conflict_level {
        ($vi: expr) => {
            path_cnt += 1;
            //## Conflict-Side Rewarding
            asg.reward_at_analysis($vi);
        };
    }
    macro_rules! trace {
        ($($arg: expr),*) => {
            #[cfg(feature = "trace_analysis")]
            println!($($arg),*);
        };
    }
    /// a logging facility
    macro_rules! trace_lit {
        ($lit: expr, $message: expr) => {
            #[cfg(feature = "trace_analysis")]
            {
                let vi = $lit.vi();
                let lv = asg.level(vi);
                println!("{}: literal {} at level {}", $message, i32::from($lit), $lv);
            }
        };
    }
    /// vi must be assigned at the current or lower decision level
    macro_rules! validate_vi {
        ($vi: expr) => {
            debug_assert!(!asg.var($vi).is(FlagVar::ELIMINATED));
            debug_assert!(
                asg.assign($vi).is_some(),
                "conflict_analyze(validate_vi) found unassigned: {:?}",
                $vi
            );
            debug_assert!(asg.level($vi) <= dl);
        };
    }
    macro_rules! set_seen {
        ($vi: expr) => {
            debug_assert!(!asg.var($vi).is(FlagVar::CA_SEEN));
            asg.var_mut($vi).turn_on(FlagVar::CA_SEEN);
        };
    }
    macro_rules! boundary_check {
        ($condition: expr, $($arg: expr),+) => {
            #[cfg(feature = "boundary_check")]
            {
                if !$condition {
                    dbg!(cc);
                    dbg!(dl);
                    tracer(asg, cdb);
                    println!("Learnt clause so far: {}",
                             learnt.report(asg)
                             .iter()
                             .map(|r| format!("  {:?}", r))
                             .collect::<Vec<String>>()
                             .join("\n")
                    );
                    panic!($($arg),*);
                }
            }
        };
    }

    {
        trace_lit!("- handle conflicting literal", p);
        let vi = p.vi();
        if asg.var(vi).assign.is_none() {
            println!("L355: {cc:?}");
            println!(
                " - dl: {}, cc.0.level {}",
                asg.decision_level(),
                asg.var(cc.0.vi()).level
            );
        }
        validate_vi!(vi);
        set_seen!(vi);
        let lvl = asg.level(vi);
        if dl == lvl {
            conflict_level!(vi);
        } else {
            debug_assert_ne!(root_level, lvl);
            learnt.push(p);
        }
    }
    let mut trail_index = asg.stack_len() - 1;
    let mut max_lbd: u16 = 0;
    let mut cid_with_max_lbd: Option<ClauseId> = None;
    loop {
        match reason {
            AssignReason::BinaryLink(l) => {
                // Always collect LRAT hint for the binary clause [!l, p],
                // even if l's variable was already SEEN.  The hint is needed
                // by the LRAT checker regardless of whether we still need to
                // traverse the variable in the implication graph.
                #[cfg(not(feature = "no_IO"))]
                {
                    let bcid = cdb
                        .binary_links(!l)
                        .iter()
                        .find(|(ol, _)| *ol == p)
                        .map(|(_, cid)| *cid);
                    if let Some(bcid) = bcid {
                        state.lrat_hints.push(cdb[bcid].lrat_id);
                    }
                }
                let vi = l.vi();
                if !asg.var(vi).is(FlagVar::CA_SEEN) {
                    validate_vi!(vi);
                    let lvl = asg.level(vi);
                    if root_level == lvl {
                        // Collect LRAT hint for root-level literal
                        #[cfg(not(feature = "no_IO"))]
                        {
                            let rid = state.lrat_root_ids[vi];
                            if rid != 0 {
                                state.lrat_hints.push(rid);
                            }
                        }
                        trace_lit!(l, " -- ignore root level");
                    } else {
                        set_seen!(vi);
                        trace_lit!(l, " - binary linked");
                        if dl == lvl {
                            trace_lit!(l, " -- found another path");
                            conflict_level!(vi);
                        } else {
                            trace_lit!(l, " -- push to earnt");
                            // This path is created for chrono-BT.
                            // So we must consider if `l` should be pushed or `!l`.
                            // From debug log, it seems to be `!l`.
                            learnt.push(!l);
                        }
                    }
                }
            }
            AssignReason::Implication(cid) => {
                trace!(
                    "analyze clause {}(first literal: {}) for {}",
                    cid,
                    i32::from(cdb[cid].lit0()),
                    p
                );
                debug_assert!(!cdb[cid].is_dead() && 2 < cdb[cid].len());
                // Collect LRAT hint
                #[cfg(not(feature = "no_IO"))]
                state.lrat_hints.push(cdb[cid].lrat_id);
                // if !cdb.update_at_analysis(asg, cid) {
                if !cdb[cid].is(FlagClause::LEARNT) {
                    cdb[cid].used = cdb[cid].used.saturating_add(1);
                }
                if max_lbd < cdb[cid].rank {
                    max_lbd = cdb[cid].rank;
                    cid_with_max_lbd = Some(cid);
                }
                for q in cdb[cid].iter().skip(1) {
                    let vi = q.vi();
                    debug_assert!(asg.var(vi).assign.is_some());
                    // if asg.var(vi).assign.is_none() {
                    //     println!(
                    //         "Implication clause contains non-assinged lit (cc: {:?}, at level: {:?})",
                    //         cc,
                    //         asg.var(cc.0.vi()).level
                    //     );
                    //     println!("p: {:?}, level: {:?}", p, asg.var(p.vi()).level);
                    //     println!("dl: {}", asg.decision_level());
                    //     println!(
                    //         "c{:?}: {:?}",
                    //         cid,
                    //         cdb[cid]
                    //             .iter()
                    //             // .filter(|l| asg.var(l.vi()).assign.is_none())
                    //             .map(|l| (l, asg.var(l.vi()).level))
                    //             .collect::<Vec<_>>()
                    //     );
                    //     panic!();
                    // }
                    validate_vi!(vi);
                    if !asg.var(vi).is(FlagVar::CA_SEEN) {
                        let lvl = asg.level(vi);
                        if root_level == lvl {
                            // Collect LRAT hint for root-level literal: the
                            // clause that justified this root-level assignment
                            // is needed by the LRAT checker even though we
                            // don't traverse the variable further.
                            #[cfg(not(feature = "no_IO"))]
                            {
                                let rid = state.lrat_root_ids[vi];
                                if rid != 0 {
                                    state.lrat_hints.push(rid);
                                }
                            }
                            trace_lit!(q, " -- ignore");
                            continue;
                        }
                        set_seen!(vi);
                        if dl == lvl {
                            trace_lit!(q, " -- found another path");
                            conflict_level!(vi);
                        } else {
                            trace_lit!(q, " -- push to earnt");
                            learnt.push(*q);
                        }
                    } else {
                        trace!(q, " -- ignore flagged already");
                    }
                }
            }
            AssignReason::Decision(_) | AssignReason::None => {
                boundary_check!(
                    false,
                    "found a strange var {:?}:: path_cnt {}\nDecisionMap\n{}",
                    reason,
                    path_cnt,
                    asg.stack_iter()
                        .skip(trail_index)
                        .filter(|l| matches!(asg.reason(l.vi()), AssignReason::Decision(_)))
                        .map(|l| format!("{:?}", l.report(asg)))
                        .collect::<Vec<String>>()
                        .join("\n")
                );
            }
        }
        //
        // set the index of the next literal to trail_index
        //
        #[allow(clippy::blocks_in_conditions)]
        while {
            let vi = asg.stack(trail_index).vi();
            boundary_check!(
                0 < vi && vi < asg.num_vars,
                "trail[{}] has an invalid var index {}",
                trail_index,
                asg.stack(trail_index)
            );
            let lvl = asg.level(vi);
            let v = asg.var(vi);
            !v.is(FlagVar::CA_SEEN) || lvl != dl
        } {
            trace_lit!(asg.stack(trail_index), "skip, not flagged");
            boundary_check!(
                0 < trail_index,
                "Broke the bottom:: path_cnt {} scanned to {}",
                path_cnt,
                asg.stack_len() - trail_index
            );
            trail_index -= 1;
        }
        p = asg.stack(trail_index);
        trace!("move to flagged {}; num path: {}", p.vi(), path_cnt - 1);

        asg.var_mut(p.vi()).turn_off(FlagVar::CA_SEEN);
        // since the trail can contain a literal which level is under `dl` after
        // the `dl`-th decision var, we must skip it.
        path_cnt -= 1;
        if path_cnt == 0 {
            break;
        }
        debug_assert!(0 < trail_index);
        trail_index -= 1;
        reason = asg.reason(p.vi());
    }
    if let Some(cid) = cid_with_max_lbd {
        cdb.update_at_analysis(asg, cid);
    }
    // debug_assert!(learnt.iter().all(|l| *l != !p));
    debug_assert_eq!(asg.level(p.vi()), dl);
    learnt[0] = !p;
    trace!(
        "appending {}, the final (but not minimized) learnt is {:?}",
        learnt[0], learnt
    );
    // When LRAT certification is active, skip clause minimization because
    // `is_redundant` and `minimize_with_bi_clauses` traverse reason clauses
    // whose IDs are not collected into the LRAT hints.
    #[cfg(not(feature = "no_IO"))]
    if cdb.is_certification_active() {
        return find_backtrack_level(&mut state.new_learnt, asg);
    }
    minimize_learnt(&mut state.new_learnt, asg, cdb)
}

/// Compute the correct backtrack level from the learnt clause without minimizing it,
/// and clear CA_SEEN flags. Used when LRAT certification is active (minimization skipped).
#[cfg(not(feature = "no_IO"))]
fn find_backtrack_level(new_learnt: &mut Vec<Lit>, asg: &mut AssignStack) -> DecisionLevel {
    // Clear CA_SEEN for all literals in the learnt clause (they were set during analysis)
    for l in new_learnt.iter() {
        asg.var_mut(l.vi()).turn_off(FlagVar::CA_SEEN);
    }
    // Find correct backtrack level from remaining literals
    let mut level_to_return = 0;
    if 1 < new_learnt.len() {
        let mut max_i = 1;
        level_to_return = asg.level(new_learnt[max_i].vi());
        for (i, l) in new_learnt.iter().enumerate().skip(2) {
            let lv = asg.level(l.vi());
            if level_to_return < lv {
                level_to_return = lv;
                max_i = i;
            }
        }
        new_learnt.swap(1, max_i);
    }
    level_to_return
}

fn minimize_learnt(
    new_learnt: &mut Vec<Lit>,
    asg: &mut AssignStack,
    cdb: &mut ClauseDB,
) -> DecisionLevel {
    let mut to_clear: Vec<Lit> = vec![new_learnt[0]];
    let mut levels = vec![false; asg.decision_level() as usize + 1];
    for l in &new_learnt[1..] {
        to_clear.push(*l);
        levels[asg.level(l.vi()) as usize] = true;
    }
    let l0 = new_learnt[0];
    new_learnt.retain(|l| *l == l0 || !l.is_redundant(asg, cdb, &mut to_clear, &levels));
    let len = new_learnt.len();
    if 2 < len && len < 30 {
        cdb.minimize_with_bi_clauses(asg, new_learnt);
    }
    // find correct backtrack level from remaining literals
    let mut level_to_return = 0;
    if 1 < new_learnt.len() {
        let mut max_i = 1;
        level_to_return = asg.level(new_learnt[max_i].vi());
        for (i, l) in new_learnt.iter().enumerate().skip(2) {
            let lv = asg.level(l.vi());
            if level_to_return < lv {
                level_to_return = lv;
                max_i = i;
            }
        }
        new_learnt.swap(1, max_i);
    }
    for l in &to_clear {
        asg.var_mut(l.vi()).turn_off(FlagVar::CA_SEEN);
    }
    level_to_return
}

/// return `true` if the `lit` is redundant, which is defined by
/// any leaf of implication graph for it isn't an asserted var nor a decision var.
impl Lit {
    fn is_redundant(
        self,
        asg: &mut AssignStack,
        cdb: &ClauseDB,
        clear: &mut Vec<Lit>,
        levels: &[bool],
    ) -> bool {
        if matches!(asg.reason(self.vi()), AssignReason::Decision(_)) {
            return false;
        }
        let mut stack = vec![self];
        let top = clear.len();
        while let Some(sl) = stack.pop() {
            match asg.reason(sl.vi()) {
                AssignReason::BinaryLink(l) => {
                    let vi = l.vi();
                    let lv = asg.level(vi);
                    if 0 < lv && !asg.var(vi).is(FlagVar::CA_SEEN) {
                        // if asg.reason(vi) != AssignReason::Decision(_) && levels[lv as usize] {
                        if matches!(
                            asg.reason(vi),
                            AssignReason::Implication(_) | AssignReason::BinaryLink(_)
                        ) && levels[lv as usize]
                        {
                            asg.var_mut(vi).turn_on(FlagVar::CA_SEEN);
                            stack.push(l);
                            clear.push(l);
                        } else {
                            // one of the roots is a decision var at an unchecked level.
                            for l in &clear[top..] {
                                asg.var_mut(l.vi()).turn_off(FlagVar::CA_SEEN);
                            }
                            clear.truncate(top);
                            return false;
                        }
                    }
                }
                AssignReason::Implication(cid) => {
                    let c = &cdb[cid];
                    for q in &(*c)[1..] {
                        let vi = q.vi();
                        let lv = asg.level(vi);
                        if 0 < lv && !asg.var(vi).is(FlagVar::CA_SEEN) {
                            // if asg.reason(vi) != AssignReason::default() && levels[lv as usize] {
                            if matches!(
                                asg.reason(vi),
                                AssignReason::BinaryLink(_) | AssignReason::Implication(_)
                            ) && levels[lv as usize]
                            {
                                asg.var_mut(vi).turn_on(FlagVar::CA_SEEN);
                                stack.push(*q);
                                clear.push(*q);
                            } else {
                                // one of the roots is a decision var at an unchecked level.
                                for l in &clear[top..] {
                                    asg.var_mut(l.vi()).turn_off(FlagVar::CA_SEEN);
                                }
                                clear.truncate(top);
                                return false;
                            }
                        }
                    }
                }
                AssignReason::Decision(_) | AssignReason::None => unreachable!("is_redundant"),
            }
        }
        true
    }
}

#[allow(dead_code)]
fn check_graph(asg: &AssignStack, cdb: &ClauseDB, lit: Lit, mes: &str) {
    let its_level = asg.level(lit.vi());
    let mut children = Vec::new();
    let precedents = lit_level(asg, cdb, lit, &mut children, mes);
    assert!(precedents <= its_level);
}

#[allow(dead_code)]
fn lit_level(
    asg: &AssignStack,
    cdb: &ClauseDB,
    lit: Lit,
    bag: &mut Vec<Lit>,
    _mes: &str,
) -> DecisionLevel {
    if bag.contains(&lit) {
        return 0;
    }
    bag.push(lit);
    match asg.reason(lit.vi()) {
        AssignReason::Decision(0) => asg.root_level(),
        AssignReason::Decision(lvl) => lvl,
        AssignReason::Implication(cid) => {
            assert_eq!(
                cdb[cid].lit0(),
                lit,
                "lit0 {} != lit{}, cid {}, {}",
                cdb[cid].lit0(),
                lit,
                cid,
                &cdb[cid]
            );
            // assert!(
            //     !bag.contains(&lit),
            //     "{}; {} is contained in {:?}\n{:?}\n{}",
            //     mes,
            //     lit,
            //     bag,
            //     asg.reason(lit.vi()),
            //     dumper(asg, cdb, bag),
            // );
            // bag.push(lit);
            cdb[cid]
                .iter()
                .skip(1)
                .map(|l| lit_level(asg, cdb, !*l, bag, _mes))
                .max()
                .unwrap()
        }
        AssignReason::BinaryLink(b) => lit_level(asg, cdb, b, bag, _mes),
        AssignReason::None => panic!("One of root of {lit} isn't assigned."),
    }
}

#[allow(dead_code)]
fn dumper(asg: &AssignStack, cdb: &ClauseDB, bag: &[Lit]) -> String {
    use std::fmt::Write as _;
    let mut s = String::new();
    for l in bag {
        writeln!(
            s,
            "{:8>} :: level {:4>}, {:?} {:?}",
            *l,
            asg.level(l.vi()),
            asg.reason(l.vi()),
            match asg.reason(l.vi()) {
                AssignReason::Decision(_) => vec![],
                AssignReason::BinaryLink(lit) => vec![*l, !lit],
                AssignReason::Implication(cid) => cdb[cid].iter().copied().collect::<Vec<Lit>>(),
                AssignReason::None => vec![],
            },
        )
        .unwrap();
    }
    s
}

#[cfg(feature = "boundary_check")]
fn tracer(asg: &AssignStack, cdb: &ClauseDB) {
    use std::io::{self, Write};
    loop {
        let mut input = String::new();
        print!("cid(or 0 for quit): ");
        std::io::stdout().flush().expect("IO error");
        io::stdin().read_line(&mut input).expect("IO error");
        if input.is_empty() {
            break;
        }
        let Ok(cid) = input.trim().parse::<usize>() else {
            continue;
        };
        if cid == 0 {
            break;
        }
        println!(
            "{}",
            cdb[ClauseId::from(cid)]
                .report(asg)
                .iter()
                .map(|r| format!(
                    " {}{:?}",
                    asg.var(Lit::from(r.lit).vi())
                        .is(FlagVar::CA_SEEN)
                        .then(|| "S")
                        .unwrap_or(" "),
                    r
                ))
                .collect::<Vec<String>>()
                .join("\n"),
        );
    }
    panic!("done");
}
